apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mnist-acr-d
spec:
  template:
    metadata:
      labels:
        app: mnist-acr
    spec:
      containers:
      - name: mnist
        image: slash2acr.azurecr.io/mlflow/mnist-keras
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acrsecret


